Loader
Maryna-Hemb/filmoteka-project-team-12 pull request #4
Opened 2023-02-03 21:47 UTC by ViktoriiaSlobodeniuk

2023-02-03 23:10 UTC, Maryna-Hemb requested changes

2023-02-03 23:10 UTC, Maryna-Hemb commented on src/js/loader.js
> +class Loader {
Наскільки я розумію цей клас далі буде перевикористовуватись на інших функціях, тому йому, мені здається, треба зробити export class Loader

2023-02-04 10:03 UTC, ViktoriiaSlobodeniuk commented on src/js/loader.js
> +class Loader {
додала експорт)

2023-02-04 11:15 UTC, Maryna-Hemb approved these changes

2023-02-04 11:15 UTC, merged